---
title: "Lab 3 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Setup
1. Login to the lab computer.    
2. Navigate to github.com and login.  
3. Find the class repository "datascibiol" (https://github.com/jmledford3115/datascibiol).  
4. Download a copy the class repository to the desktop.  
5. Clone your repository to the desktop using GitHub Desktop.  
6. Copy the files for today's lab from the class repository and paste them into **your** repository.  
7. Open today's lab in RStudio.  

## Review from last time
### *With a partner, discuss the following questions*
1. What is a path? How do we know that we have a correct path?
A path is a location of a file.
2. What is a local path? What is a global path?
A local path is a path on your own computer. A global path could be something in the cloud that can be accessed publically, such as through a URL.
3. How does a path relate to a working directory in R?


## Shut Down Procedures
1. Save your work.  
2. Commit and push your work to GitHub using GitHub Desktop.  
3. Delete your repository from the desktop.  
4. Delete the class repository from the desktop.  
5. Log out of the computer.  